config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  resources :event_categories
  resources :event_organizers
  resources :events
  root to: "home#index"
  get '/tagged', to: "events#tagged", as: :tagged
  namespace :admin do
    resources :event_categories
    resources :event_organizers
    resources :events
  end
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :event_organizer,optional: :true
  belongs_to :event_category,optional: :true
  extend FriendlyId
  friendly_id :name, use: :slugged
  acts_as_taggable
  mount_uploader :cover_image, CoverImageUploader
  geocoded_by :venue             # can also be an IP address
  after_validation :geocode          # auto-fetch coordinates
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to admin_event_path(@event), notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to admin_event_path(@event), notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_admin_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def tagged
  if params[:tag].present?
    @events = Event.tagged_with(params[:tag])
  else
    @events = Event.all
  end
end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :description, :city, :state, :country, :venue, :latitude, :longitude, :cover_image, :event_organizer_id, :event_category_id, :is_featured, :slug, :tag_list)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def tagged
  if params[:tag].present?
    @events = Event.tagged_with(params[:tag])
  else
    @events = Event.all
  end
end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :description, :city, :state, :country, :venue, :latitude, :longitude, :cover_image, :event_organizer_id, :event_category_id, :is_featured, :slug, :tag_list)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

    <ul>
      <% event.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, id: :event_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, id: :event_description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :venue %>
    <%= form.text_field :venue, id: :event_venue, class: "form-control", id: "autocomplete", placeholder: "Enter your venue", 
          onFocus: "geolocate()"  %>
  </div>
  <div class="row">
    <div class="col-md-4">
      <div class="form-group">
        <%= form.label :city %>
        <%= form.text_field :city, id: :event_city, class: "form-control" %>
      </div>
    </div>
    <div class="col-md-4">
      <div class="form-group">
        <%= form.label :state %>
        <%= form.text_field :state, id: :event_state, class: "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <%= form.label :country %>
      <%= form.text_field :country, id: :event_country, class: "form-control" %>
    </div>


    <div class="col-md-4">
      <div class="form-group">
        <%= form.label :latitude %>
        <%= form.text_field :latitude, id: :event_latitude, class: "form-control"  %>
      </div>
    </div>

    <div class="col-md-4">
      <div class="form-group">
        <%= form.label :longitude %>
        <%= form.text_field :longitude, id: :event_longitude, class: "form-control"  %>
      </div>
    </div>
    <div class="col-md-4">
      <div class="form-group">
        <%= form.label :cover_image %><br>
        <%= form.file_field :cover_image, id: :event_cover_image  %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :event_organizer_id %>
    <%= form.text_field :event_organizer_id, id: :event_event_organizer_id, class: "form-control"  %>
  </div>

  <div class="form-group">
    <%= form.label :event_category_id %>
    <%= form.text_field :event_category_id, id: :event_event_category_id, class: "form-control"  %>
  </div>


  <div class="form-group">
    <%= form.label :slug %>
    <%= form.text_field :slug, id: :event_slug, class: "form-control"  %>
  </div>
  <div class='field'>
    <%= form.label :tag_list, 'Tags (separated by commas)' %><br/>
    <%= form.text_field :tag_list, class: "form-control" %>
  </div>
  <br>
  <div class="form-group">
    <%= form.label :is_featured %><br>
    <%= form.check_box :is_featured, id: :event_is_featured %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

<script>
      // This example displays an address form, using the autocomplete feature
      // of the Google Places API to help users fill in the information.

      // This example requires the Places library. Include the libraries=places
      // parameter when you first load the API. For example:
      // <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&libraries=places">

      var placeSearch, autocomplete;
      var componentForm = {
        street_number: 'short_name',
        route: 'long_name',
        locality: 'long_name',
        administrative_area_level_1: 'short_name',
        country: 'long_name',
        postal_code: 'short_name'
      };

      function initAutocomplete() {
        // Create the autocomplete object, restricting the search to geographical
        // location types.
        autocomplete = new google.maps.places.Autocomplete(
            /** @type {!HTMLInputElement} */(document.getElementById('autocomplete')),
            {types: ['geocode']});

        // When the user selects an address from the dropdown, populate the address
        // fields in the form.
        autocomplete.addListener('place_changed', fillInAddress);
      }

      function fillInAddress() {
        // Get the place details from the autocomplete object.
        var place = autocomplete.getPlace();

        $("#latitude").val(place.geometry.location.lat());
        $("#longitude").val(place.geometry.location.lng());

        for (var component in componentForm) {
          document.getElementById(component).value = '';
          document.getElementById(component).disabled = false;
        }

        // Get each component of the address from the place details
        // and fill the corresponding field on the form.
        for (var i = 0; i < place.address_components.length; i++) {
          var addressType = place.address_components[i].types[0];
          if (componentForm[addressType]) {
            var val = place.address_components[i][componentForm[addressType]];
            document.getElementById(addressType).value = val;
          }
        }
      }

      // Bias the autocomplete object to the user's geographical location,
      // as supplied by the browser's 'navigator.geolocation' object.
      function geolocate() {
        if (navigator.geolocation) {
          navigator.geolocation.getCurrentPosition(function(position) {
            var geolocation = {
              lat: position.coords.latitude,
              lng: position.coords.longitude
            };
            var circle = new google.maps.Circle({
              center: geolocation,
              radius: position.coords.accuracy
            });
            autocomplete.setBounds(circle.getBounds());
          });
        }
      }
      

      function showResult(result) {
    document.getElementById('latitude').value = result.geometry.location.lat();
    document.getElementById('longitude').value = result.geometry.location.lng();
}
    </script>
      <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBFBYM37YGMTdgkEp9fipPljSjprTDZL8Y&libraries&libraries=places&callback=initAutocomplete" async defer></script>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Events</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>City</th>
      <th>State</th>
      <th>Country</th>
      <th>Venue</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Cover image</th>
      <th>Event organizer</th>
      <th>Event category</th>
      <th>Is featured</th>
      <th>Slug</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.name %></td>
        <td><%= event.description %></td>
        <td><%= event.city %></td>
        <td><%= event.state %></td>
        <td><%= event.country %></td>
        <td><%= event.venue %></td>
        <td><%= event.latitude %></td>
        <td><%= event.longitude %></td>
        <td><%= event.cover_image %></td>
        <td><%= event.event_organizer %></td>
        <td><%= event.event_category %></td>
        <td><%= event.is_featured %></td>
        <td><%= event.slug %></td>
        <p><% event.tag_list.each do |tag| %>
          <%= link_to tag, tagged_path(tag: tag) %>
          <% end %></p>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<div class="container">
  <div class="col-md-8 offset-md-2">
    <div class="card mt-5">
      <h1 class="card-header">New Event</h1>
      <div class="card-body">
        <%= render 'form', event: @event %>
        <%= link_to 'Back', events_path %>
      </div>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @event.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>

<p>
  <strong>City:</strong>
  <%= @event.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @event.state %>
</p>

<p>
  <strong>Country:</strong>
  <%= @event.country %>
</p>

<p>
  <strong>Venue:</strong>
  <%= @event.venue %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @event.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @event.longitude %>
</p>

<p>
  <strong>Cover image:</strong>
  <%= image_tag @event.cover_image_url %>
</p>

<p>
  <strong>Event organizer:</strong>
  <%= @event.event_organizer %>
</p>

<p>
  <strong>Event category:</strong>
  <%= @event.event_category %>
</p>

<p>
  <strong>Is featured:</strong>
  <%= @event.is_featured %>
</p>

<p>
  <strong>Slug:</strong>
  <%= @event.slug %>
</p>

<p>Tags: <%= @event.tag_list %></p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>