config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  resources :event_categories
  resources :event_organizers
  resources :events
  root to: "home#index"
  get '/tagged', to: "events#tagged", as: :tagged
  namespace :admin do
    resources :event_categories
    resources :event_organizers
    resources :events
  end
end

app/models/event_organizer.rb
class EventOrganizer < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged
  geocoded_by :address             # can also be an IP address
  after_validation :geocode          # auto-fetch coordinates
end

app/controllers/admin/event_organizers_controller.rb
class Admin::EventOrganizersController < ApplicationController
  before_action :set_event_organizer, only: [:show, :edit, :update, :destroy]

  # GET /event_organizers
  # GET /event_organizers.json
  def index
    @event_organizers = EventOrganizer.all
  end

  # GET /event_organizers/1
  # GET /event_organizers/1.json
  def show
  end

  # GET /event_organizers/new
  def new
    @event_organizer = EventOrganizer.new
  end

  # GET /event_organizers/1/edit
  def edit
  end

  # POST /event_organizers
  # POST /event_organizers.json
  def create
    @event_organizer = EventOrganizer.new(event_organizer_params)

    respond_to do |format|
      if @event_organizer.save
        format.html { redirect_to admin_event_organizer_path(@event_organizer), notice: 'Event organizer was successfully created.' }
        format.json { render :show, status: :created, location: @event_organizer }
      else
        format.html { render :new }
        format.json { render json: @event_organizer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /event_organizers/1
  # PATCH/PUT /event_organizers/1.json
  def update
    respond_to do |format|
      if @event_organizer.update(event_organizer_params)
        format.html { redirect_to admin_event_organizer_path(@event_organizer), notice: 'Event organizer was successfully updated.' }
        format.json { render :show, status: :ok, location: @event_organizer }
      else
        format.html { render :edit }
        format.json { render json: @event_organizer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /event_organizers/1
  # DELETE /event_organizers/1.json
  def destroy
    @event_organizer.destroy
    respond_to do |format|
      format.html { redirect_to admin_event_organizers_url, notice: 'Event organizer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event_organizer
      @event_organizer = EventOrganizer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_organizer_params
      params.require(:event_organizer).permit(:name, :email, :address, :city, :state, :country, :latitude, :longitude, :logo_image, :contact, :slug)
    end
end

app/controllers/event_organizers_controller.rb
class EventOrganizersController < ApplicationController
  before_action :set_event_organizer, only: [:show, :edit, :update, :destroy]

  # GET /event_organizers
  # GET /event_organizers.json
  def index
    @event_organizers = EventOrganizer.all
  end

  # GET /event_organizers/1
  # GET /event_organizers/1.json
  def show
  end

  # GET /event_organizers/new
  def new
    @event_organizer = EventOrganizer.new
  end

  # GET /event_organizers/1/edit
  def edit
  end

  # POST /event_organizers
  # POST /event_organizers.json
  def create
    @event_organizer = EventOrganizer.new(event_organizer_params)

    respond_to do |format|
      if @event_organizer.save
        format.html { redirect_to @event_organizer, notice: 'Event organizer was successfully created.' }
        format.json { render :show, status: :created, location: @event_organizer }
      else
        format.html { render :new }
        format.json { render json: @event_organizer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /event_organizers/1
  # PATCH/PUT /event_organizers/1.json
  def update
    respond_to do |format|
      if @event_organizer.update(event_organizer_params)
        format.html { redirect_to @event_organizer, notice: 'Event organizer was successfully updated.' }
        format.json { render :show, status: :ok, location: @event_organizer }
      else
        format.html { render :edit }
        format.json { render json: @event_organizer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /event_organizers/1
  # DELETE /event_organizers/1.json
  def destroy
    @event_organizer.destroy
    respond_to do |format|
      format.html { redirect_to event_organizers_url, notice: 'Event organizer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event_organizer
      @event_organizer = EventOrganizer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_organizer_params
      params.require(:event_organizer).permit(:name, :email, :address, :city, :state, :country, :latitude, :longitude, :logo_image, :contact, :slug)
    end
end

app/helpers/event_organizers_helper.rb
module EventOrganizersHelper
end

app/views/admin/event_organizers/_form.html.erb
<%= form_for([:admin, @event_organizer])do |form| %>
  <% if event_organizer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event_organizer.errors.count, "error") %> prohibited this event_organizer from being saved:</h2>

      <ul>
      <% event_organizer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, id: :event_organizer_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :email %>
    <%= form.email_field :email, id: :event_organizer_email, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :address %>
    <%= form.text_field :address, id: :event_organizer_address, class: "form-control", id: "autocomplete", placeholder: "Enter your address", onFocus: "geolocate()"  %>
  </div>
  <div class="row">
      <div class="col-md-4">
        <div class="form-group">
          <%= form.label :city %>
          <%= form.text_field :city, id: :event_organizer_city, class: "form-control" %>
        </div>
      </div>
    <div class="col-md-4">
      <div class="form-group">
        <%= form.label :state %>
        <%= form.text_field :state, id: :event_organizer_state, class: "form-control" %>
      </div>
      </div>
    <div class="col-md-4">
      <div class="form-group">
        <%= form.label :country %>
        <%= form.text_field :country, id: :event_organizer_country, class: "form-control" %>
      </div>
    </div>
    <div class="col-md-4">
      <div class="form-group">
        <%= form.label :latitude %>
        <%= form.text_field :latitude, id: :event_organizer_latitude, class: "form-control" %>
      </div>
    </div>
    <div class="col-md-4">
      <div class="field">
        <%= form.label :longitude %>
        <%= form.text_field :longitude, id: :event_organizer_longitude, class: "form-control" %>
      </div>
    </div>
    <div class="col-md-4">
      <div class="form-group">
        <%= form.label :logo_image %><br>
        <%= form.file_field :logo_image, id: :event_organizer_logo_image %>
      </div>
    </div>


    <div class="col-md-6">
      <div class="form-group">
        <%= form.label :contact %>
        <%= form.number_field :contact, id: :event_organizer_contact, class: "form-control" %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="form-group">
        <%= form.label :slug %>
        <%= form.text_field :slug, id: :event_organizer_slug, class: "form-control" %>
      </div>
    </div>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>


<script>
      // This example displays an address form, using the autocomplete feature
      // of the Google Places API to help users fill in the information.

      // This example requires the Places library. Include the libraries=places
      // parameter when you first load the API. For example:
      // <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&libraries=places">

      var placeSearch, autocomplete;
      var componentForm = {
        street_number: 'short_name',
        route: 'long_name',
        locality: 'long_name',
        administrative_area_level_1: 'short_name',
        country: 'long_name',
        postal_code: 'short_name'
      };

      function initAutocomplete() {
        // Create the autocomplete object, restricting the search to geographical
        // location types.
        autocomplete = new google.maps.places.Autocomplete(
            /** @type {!HTMLInputElement} */(document.getElementById('autocomplete')),
            {types: ['geocode']});

        // When the user selects an address from the dropdown, populate the address
        // fields in the form.
        autocomplete.addListener('place_changed', fillInAddress);
      }

      function fillInAddress() {
        // Get the place details from the autocomplete object.
        var place = autocomplete.getPlace();

        $("#latitude").val(place.geometry.location.lat());
        $("#longitude").val(place.geometry.location.lng());

        for (var component in componentForm) {
          document.getElementById(component).value = '';
          document.getElementById(component).disabled = false;
        }

        // Get each component of the address from the place details
        // and fill the corresponding field on the form.
        for (var i = 0; i < place.address_components.length; i++) {
          var addressType = place.address_components[i].types[0];
          if (componentForm[addressType]) {
            var val = place.address_components[i][componentForm[addressType]];
            document.getElementById(addressType).value = val;
          }
        }
      }

      // Bias the autocomplete object to the user's geographical location,
      // as supplied by the browser's 'navigator.geolocation' object.
      function geolocate() {
        if (navigator.geolocation) {
          navigator.geolocation.getCurrentPosition(function(position) {
            var geolocation = {
              lat: position.coords.latitude,
              lng: position.coords.longitude
            };
            var circle = new google.maps.Circle({
              center: geolocation,
              radius: position.coords.accuracy
            });
            autocomplete.setBounds(circle.getBounds());
          });
        }
      }
      

      function showResult(result) {
    document.getElementById('latitude').value = result.geometry.location.lat();
    document.getElementById('longitude').value = result.geometry.location.lng();
}
    </script>
      <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBFBYM37YGMTdgkEp9fipPljSjprTDZL8Y&libraries&libraries=places&callback=initAutocomplete" async defer></script>

app/views/admin/event_organizers/edit.html.erb
<h1>Editing Event Organizer</h1>

<%= render 'form', event_organizer: @event_organizer %>

<%= link_to 'Show', admin_event_organizers_path(@event_organizer) %> |
<%= link_to 'Back', admin_event_organizers_path %>

app/views/admin/event_organizers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Event Organizers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Address</th>
      <th>City</th>
      <th>State</th>
      <th>Country</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Logo image</th>
      <th>Contact</th>
      <th>Slug</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @event_organizers.each do |event_organizer| %>
      <tr>
        <td><%= event_organizer.name %></td>
        <td><%= event_organizer.email %></td>
        <td><%= event_organizer.address %></td>
        <td><%= event_organizer.city %></td>
        <td><%= event_organizer.state %></td>
        <td><%= event_organizer.country %></td>
        <td><%= event_organizer.latitude %></td>
        <td><%= event_organizer.longitude %></td>
        <td><%= event_organizer.logo_image %></td>
        <td><%= event_organizer.contact %></td>
        <td><%= event_organizer.slug %></td>
        <td><%= link_to 'Show', admin_event_organizer %></td>
        <td><%= link_to 'Edit', edit_admin_event_organizer_path(event_organizer) %></td>
        <td><%= link_to 'Destroy', admin_event_organizer_path(event_organizer), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event Organizer', new_event_organizer_path %>

app/views/admin/event_organizers/new.html.erb
<div class="container">
  <div class="col-md-8 offset-md-2">
    <div class="card mt-5">
      <h1 class="card-header">New Event Organizer</h1>
      <div class="card-body">
        <%= render 'form', event_organizer: @event_organizer %>
        <%= link_to 'Back', admin_event_organizers_path %>
      </div>
    </div>
  </div>
</div>

app/views/admin/event_organizers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @event_organizer.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @event_organizer.email %>
</p>

<p>
  <strong>Address:</strong>
  <%= @event_organizer.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @event_organizer.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @event_organizer.state %>
</p>

<p>
  <strong>Country:</strong>
  <%= @event_organizer.country %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @event_organizer.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @event_organizer.longitude %>
</p>

<p>
  <strong>Logo image:</strong>
  <%= @event_organizer.logo_image %>
</p>

<p>
  <strong>Contact:</strong>
  <%= @event_organizer.contact %>
</p>

<p>
  <strong>Slug:</strong>
  <%= @event_organizer.slug %>
</p>

<%= link_to 'Edit', edit_admin_event_organizer_path(@event_organizer) %> |
<%= link_to 'Back', admin_event_organizers_path %>